[package]
name = "sciadv"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
once_cell = "1.21.3"
ratatui = "0.28.1"
crossterm = "0.28.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
